services:
  firestore:
    image: gcr.io/google.com/cloudsdktool/google-cloud-cli:emulators
    command: gcloud emulators firestore start --host-port=0.0.0.0:8080
    ports:
      - "8080:8080"

  storage:
    image: fsouza/fake-gcs-server
    command: -scheme http -host 0.0.0.0 -port 4443 -backend memory
    ports:
      - "4443:4443"
    environment:
      - STORAGE_BASE_URL=http://localhost:4443

  pubsub:
    image: gcr.io/google.com/cloudsdktool/google-cloud-cli:emulators
    command: gcloud emulators pubsub start --host-port=0.0.0.0:8085
    ports:
      - "8085:8085"

  test-api:
    build: ./services/test-api
    ports:
      - "3000:3000"
    environment:
      - FIRESTORE_EMULATOR_HOST=firestore:8080
      - STORAGE_EMULATOR_HOST=http://storage:4443
      - PUBSUB_EMULATOR_HOST=pubsub:8085
    depends_on:
      - firestore
      - storage
      - pubsub